spring:
   jpa:
      hibernate:
         ddl-auto: create
   flyway:
      locations: classpath:db/migration/h2
      schemas: hop_flyway
management:
   endpoints:
      web:
         exposure:
            include: health,info

application:
   feature1: application_feature1_local
   env:
      feature1: application_env_feature1_local
service:
   feature1: service_feature1_local
   env:
      feature1: service_feature1_local
vault_key1 : vault_key1
vault_key2 : vault_key2