spring:
   datasource:
      url: jdbc:mysql://localhost:3306/tlms
      username: root
      password: 123456
# Configure actual data sources
   shardingsphere:
      datasource:
         names: ds0,ds1
         ds0:
            type: org.apache.commons.dbcp2.BasicDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/ds0
            username: root
            password: 123456
         ds1:
            type: org.apache.commons.dbcp2.BasicDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/ds1
            username: root
            password: 123456
      rules:
         sharding:
            tables:
               t_order:
                  actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
                  database-strategy:
                     standard:
                        sharding-column: user_id
                        sharding-algorithm-name: database_inline
                  table-strategy:
                     standard:
                        sharding-column: order_id
                        sharding-algorithm-name: table_inline
            sharding-algorithms:
               database_inline:
                  type: INLINE
                  props:
                     algorithm-expression: ds_${user_id % 2}
               table_inline:
                  type: INLINE
                  props:
                     algorithm-expression: t_order_${order_id % 2}